@echo off
@echo ...
@REM Uncomment the following line if you want to keep this BAT file for later use.
@REM copy "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\execAfter.bat" "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\execAfter_bak.bat" > NUL:
@REM If user didn't provide his own vsdocman_overrides.css in external files, copy the default (empty) one.
echo IF NOT EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\vsdocman_overrides.css" copy "C:\Program Files\VSdocman\Templates\vsdocman_overrides.css" "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\vsdocman_overrides.css" > NUL:
IF NOT EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\vsdocman_overrides.css" copy "C:\Program Files\VSdocman\Templates\vsdocman_overrides.css" "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\vsdocman_overrides.css" > NUL:
@echo Creating dynamic TOC...
echo IF EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\toc--" rmdir "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\toc--" /S /Q > NUL:
IF EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\toc--" rmdir "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\toc--" /S /Q > NUL:
@"C:\Program Files\VSdocman\Templates\HTML\Util\Helixoft.DynamicTocCreator.exe" /outputDirectory "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\toc--" "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\static_toc.xml"
@IF ERRORLEVEL 1 GOTO dynTocError
echo IF EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\static_toc.xml" del "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\static_toc.xml" > NUL:
IF EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\static_toc.xml" del "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\static_toc.xml" > NUL:
@:dynTocError
@echo Creating search index...
@"C:\Program Files\VSdocman\Templates\HTML\Util\HelixoftHtmlIndexer.exe" "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc" "*.htm?" "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\search--" version2
echo IF EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\msdn2019" rmdir "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\msdn2019" /S /Q > NUL:
IF EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\msdn2019" rmdir "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\msdn2019" /S /Q > NUL:
echo mkdir "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\msdn2019" > NUL:
mkdir "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\msdn2019" > NUL:
echo copy "C:\Program Files\VSdocman\Templates\msdn2019\*.*" "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\msdn2019\*.*" > NUL:
copy "C:\Program Files\VSdocman\Templates\msdn2019\*.*" "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\msdn2019\*.*" > NUL:
echo IF EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SyntaxHighlighter" rmdir "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SyntaxHighlighter" /S /Q > NUL:
IF EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SyntaxHighlighter" rmdir "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SyntaxHighlighter" /S /Q > NUL:
echo mkdir "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SyntaxHighlighter" > NUL:
mkdir "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SyntaxHighlighter" > NUL:
echo xcopy "C:\Program Files\VSdocman\Templates\SyntaxHighlighter\*.*" "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SyntaxHighlighter" /S /H /R /Y /i > NUL:
xcopy "C:\Program Files\VSdocman\Templates\SyntaxHighlighter\*.*" "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SyntaxHighlighter" /S /H /R /Y /i > NUL:
@REM HTML files that were protected against indexing will be made HTML again.
echo ren "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\*.html_rename" "*.html" > NUL:
ren "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\*.html_rename" "*.html" > NUL:
@REM delete unused files
echo IF EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SOLUTION-WIDE PROPERTIES.hhk" del "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SOLUTION-WIDE PROPERTIES.hhk" > NUL:
IF EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SOLUTION-WIDE PROPERTIES.hhk" del "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SOLUTION-WIDE PROPERTIES.hhk" > NUL:
echo IF EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SOLUTION-WIDE PROPERTIES.hhc" del "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SOLUTION-WIDE PROPERTIES.hhc" > NUL:
IF EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SOLUTION-WIDE PROPERTIES.hhc" del "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SOLUTION-WIDE PROPERTIES.hhc" > NUL:
echo IF EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SOLUTION-WIDE PROPERTIES.hhp" del "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SOLUTION-WIDE PROPERTIES.hhp" > NUL:
IF EXIST "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SOLUTION-WIDE PROPERTIES.hhp" del "D:\UNIVERSIDAD\8 OCTAVO SEMESTRE\Verificaci¢n y Validaci¢n\ProyectoPrisionSexto\ProyectoPrisionSexto\ProyectoPrisionSexto\VSdoc\SOLUTION-WIDE PROPERTIES.hhp" > NUL:
@echo All done
